version: '3.8'

services:
  mongo:
    image: mongo
    container_name: gx-registry-mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    command: npm run start:dev
    container_name: gx-registry-server
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: 'unless-stopped'
    depends_on:
      - mongo

volumes:
  data:
    driver: local
