apiVersion: apps/v1
kind: Deployment
metadata:
  name: gx-registry-server-2206-main
  namespace: gx-lab
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gx-registry-server-2206-main
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gx-registry-server-2206-main
    spec:
      containers:
      - env:
        - name: MONGO_DATABASE
          value: trust-anchor-registry
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: test-atlas-operator-project-cluster0-gx-registry-user
              key: connectionStringStandardSrv
        - name: BASE_URL
          value: http://20.76.5.229
        image: vdxcontainerregistry2022051200.azurecr.io/gx-registry:v1.0.3
        imagePullPolicy: Always
        name: gx-registry-server-2206-main
        ports:
        - containerPort: 3000
          name: http-api
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
