apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.{{YOUR-APP-NAME-HERE}}: mongo
  template:
    metadata:
      labels:
        app.{{YOUR-APP-NAME-HERE}}: mongo
    spec:
      containers:
        - image: mongo
          name: mongo
          ports:
            - containerPort: 27017
      restartPolicy: Always
